package com.honghiepit;

public interface Constants {
    int WIDTH_SIZE_FRAME=1366;
    int HEIGHT_SIZE_FRAME=768;

    int WIDTH_SIZE_IMAGE_PANEL=650;
    int HEIGHT_SIZE_IMAGE_PANEL=600;

    int LOCATION_PANEL_ORIGIN_IMAGE_X=10;
    int LOCATION_PANEL_ORIGIN_IMAGE_Y=10;

    int LOCATION_PANEL_BLUR_IMAGE_X=WIDTH_SIZE_FRAME-WIDTH_SIZE_IMAGE_PANEL-LOCATION_PANEL_ORIGIN_IMAGE_X-20;
    int LOCATION_PANEL_BLUR_IMAGE_Y=LOCATION_PANEL_ORIGIN_IMAGE_Y;
    String NAME="Image Processing";
}
